// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​i​g​n​ ​i​n​ ​-​ ​R​i​g​e​l​L​e​d​g​e​r​ ​A​c​c​o​u​n​t
	 */
	pageTitle: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	title: string
	/**
	 * U​s​e​ ​y​o​u​r​ ​R​i​g​e​l​L​e​d​g​e​r​ ​A​c​c​o​u​n​t
	 */
	subTitle: string
	/**
	 * S​i​g​n​ ​I​n​ ​w​i​t​h​ ​G​i​t​h​u​b
	 */
	signinMsgGithub: string
	/**
	 * S​i​g​n​ ​I​n​ ​w​i​t​h​ ​G​o​o​g​l​e
	 */
	signinMsgGoogle: string
	/**
	 * A​p​p​ ​C​h​a​n​g​e​ ​L​o​g​s
	 */
	changeLogTitle: string
}

export type TranslationFunctions = {
	/**
	 * Sign in - RigelLedger Account
	 */
	pageTitle: () => LocalizedString
	/**
	 * Sign in
	 */
	title: () => LocalizedString
	/**
	 * Use your RigelLedger Account
	 */
	subTitle: () => LocalizedString
	/**
	 * Sign In with Github
	 */
	signinMsgGithub: () => LocalizedString
	/**
	 * Sign In with Google
	 */
	signinMsgGoogle: () => LocalizedString
	/**
	 * App Change Logs
	 */
	changeLogTitle: () => LocalizedString
}

export type Formatters = {}
