// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​i​g​n​ ​i​n​ ​-​ ​R​i​g​e​l​L​e​d​g​e​r​ ​A​c​c​o​u​n​t
	 */
	pageTitle: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	title: string
	/**
	 * U​s​e​ ​y​o​u​r​ ​R​i​g​e​l​L​e​d​g​e​r​ ​A​c​c​o​u​n​t
	 */
	subTitle: string
}

export type TranslationFunctions = {
	/**
	 * Sign in - RigelLedger Account
	 */
	pageTitle: () => LocalizedString
	/**
	 * Sign in
	 */
	title: () => LocalizedString
	/**
	 * Use your RigelLedger Account
	 */
	subTitle: () => LocalizedString
}

export type Formatters = {}
